# Generated by Django 3.2.7 on 2021-12-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(default='', max_length=50),
        ),
    ]
